# Generated by Django 3.1.6 on 2021-03-31 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diggers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата створення'),
        ),
        migrations.AlterField(
            model_name='postabstract',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата створення'),
        ),
    ]
